### ISSUE TITLE
Riverpod introduction todo-list

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/riverpod#2609]
This is a meta issue regarding the work related to new Riverpod users.

- [ ] Rename the current "introduction" page to "Motivation"
- [ ] Add a "Quick start" page
- [ ] Have "Why Riverpod" / "Get started" / "Install" buttons on the homepage
- [ ] It should be clear that riverpod_lint is strongly recommended
- [ ] It should be clear that flutter_hooks is discouraged for newcomers
- [ ] riverpod_generator  is highly recommended for newcomers
       That is because the "old" syntax will likely be removed once we have metaprogramming
- [ ] It should be clear that Riverpod isn't about DI, but rather about caching and reactive updates
- [ ] There should be an embedded dartpad/zapp somewhere in the first few pages to try Riverpod online
- [ ] The discord should be linked in the footer
- [ ] The footer should redirect to an FAQ page
- [ ] There should be a "contributing" file explaining how to contribute to docs/riverpod linked in the footer
- [ ] Key documentation pages should be linked in the footer
- [ ] https://twitter.com/remi_rousselet should be linked in the footer

**Comment by rawasaditya** [comment]
Provide me a mock up and I will do it quickly

**Comment by rrousselGit** [comment]
@rawasaditya You mean for the homepage? I don't have a mockup, nor do I have a designer

If you want to do something, feel free to make suggestions here. Happy to work this out together.

**Comment by lucavenir** [comment]
> It should be clear that Riverpod isn't about DI, but rather about caching and reactive updates

While I totally support this, in the past Riverpod was _also_ being advertised as a "complete replacement for dependency injection". I still use this feature a lot, day by day, especially [in this last experiment](https://github.com/lucavenir/riverpod_architecture_example).

Am I doing it wrong? It's not like I can make Riverpod and, say, GetIt work together any better.

**Comment by rrousselGit** [comment]
Well currently DI isn't the main goal. It's mainly a side effect for testing and optimizations purposes.

It depends on how well I can get the scoping lint to work.


Currently you know that family has a bit of a tendency to cause props drilling. And that I consider scoping to be too advanced.

**Comment by lucavenir** [comment]
> Which sounds a bit opposite to what someone looking for DI would expect.

Yes, I get it now. Actually, this gives me clarity on my journey with Riverpod! Anyways, it doesn't sound like a problem to me. I know about scoping / prop drilling, but you really convinced me how it isn't a _dangerous_ problem.

But again, I understand why you don't want to promote Riverpod as a DI replacement anymore. Maybe in a near future, it will.

**Comment by rrousselGit** [comment]
It'd be really great if custom_lint had an official Dart alternative.

Then it would make way more sense to force users to install custom lint rules.

I could then implement custom errors.

**Comment by lucavenir** [comment]
> It'd be really great if custom_lint had an official Dart alternative.

huh? `custom_lint` isn't made for Dart?

**Comment by rrousselGit** [comment]
It is made for Dart, but it's not an official Dart tool.
